### ISSUE TITLE
PHP 7.2 incompatible password hash with 7.3

### ISSUE THREAD

**Issue by per-lind** [bitnami/bitnami-docker-phpbb#65]
**Description**

When move a forum currently running on php 7.3 to this image with 7.2 password is no loger valid as the hashing alg used by phpbb 3.3 differs depending on the php version.

**Steps to reproduce the issue:**

1. Run a board on a host with PHP 7.3
2. Restore the database on this image
3. Not possible to login

**Describe the results you received:**

I belive it might be time to bump the PHP version to 7.3 as this is now suppored with phpbb 3.3

**Comment by miguelaeh** [comment]
Hi @per-lind ,
Thank you very much for reporting this.
We have tested phpbb with PHP 7.3 and it works fine so we will work onupgrade the PHP version.
Regards.

**Comment by per-lind** [comment]
I see now that the latest image have PHP 7.3, I still run into the same problem, apparently PHP needs to be built with the option `--with-password-argon2id` see https://www.php.net/manual/en/password.installation.php

**Comment by miguelaeh** [comment]
Hi @per-lind ,
I am sorry! I forgot to notify you.
I will test the compilation step with that new flag and release a new version if it succeeds.
Thank you again for the suggestion!
Regards.

**Comment by per-lind** [comment]
@miguelaeh sounds greate, I think you might need to install this package aswell https://packages.debian.org/buster/libargon2-1

**Comment by miguelaeh** [comment]
Hi @per-lind ,
The latest version of the image should have the requested packages and was compiled with the proper flags, could you give a try?

**Comment by per-lind** [comment]
@miguelaeh Does not look like it is working for me.
This is the image I tested with `echo $BITNAMI_IMAGE_VERSION
3.3.1-debian-10-r29`
I tried both with the forum and made a simple test file of `<?php var_dump(password_hash('password', PASSWORD_ARGON2ID)); ?>` but it will only output NULL.
I can´t see that "--with-password-argon2" in the phpinfo() Configure Command section either, but I'm not sure if it really should show there. Here is my output 
`

Build Date | Sep 3 2020 18:24:36
-- | --
Configure Command | '/bitnami/blacksmith-sandox/libphp-7.3.22/configure' '--prefix=/opt/bitnami/php' '--with-apxs2=/opt/bitnami/apache/bin/apxs' '--with-imap=/bitnami/blacksmith-sandox/imap-2007.0.0' '--with-imap-ssl' '--with-zlib-dir' '--with-zlib' '--with-libxml-dir=/usr' '--enable-soap' '--disable-rpath' '--enable-inline-optimization' '--with-bz2' '--enable-sockets' '--enable-pcntl' '--enable-exif' '--enable-bcmath' '--with-pdo-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-png-dir=/usr' '--with-openssl' '--with-libdir=/lib/x86_64-linux-gnu' '--enable-ftp' '--enable-calendar' '--with-gettext' '--with-xmlrpc' '--with-xsl' '--enable-fpm' '--with-fpm-user=daemon' '--with-fpm-group=daemon' '--enable-mbstring' '--enable-cgi' '--enable-ctype' '--enable-session' '--enable-mysqlnd' '--enable-intl' '--with-iconv' '--with-pdo_sqlite' '--with-sqlite3' '--with-readline' '--with-gmp' '--with-curl' '--with-pdo-pgsql=shared' '--with-pgsql=shared' '--with-config-file-scan-dir=/opt/bitnami/php/etc/conf.d' '--with-gd' '--with-freetype-dir=/usr' '--with-jpeg-dir=/usr' '--enable-zip' '--with-pdo-dblib=shared' '--with-tidy' '--with-ldap=/usr/' '--enable-apcu=shared'

`

**Comment by miguelaeh** [comment]
Hi @per-lind ,
Sorry for the confusion the released image was PHP, not phpbb could you check with `bitnami/phpbb` version `3.3.1-debian-10-r31` I have just released that one, and the flag is on the configure command:
```
root@75f65cf46545:/# php -i | head -n 10
phpinfo()
PHP Version => 7.3.22

System => Linux 75f65cf46545 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64
Build Date => Sep 18 2020 18:06:10
Configure Command =>  '/bitnami/blacksmith-sandox/php-7.3.22/configure'  '--prefix=/opt/bitnami/php' '--with-imap=/bitnami/blacksmith-sandox/imap-2007.0.0' '--with-imap-ssl' '--with-zlib-dir' '--with-zlib' '--with-libxml-dir=/usr' '--enable-soap' '--disable-rpath' '--enable-inline-optimization' '--with-bz2' '--enable-sockets' '--enable-pcntl' '--enable-exif' '--enable-bcmath' '--with-pdo-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-png-dir=/usr' '--with-openssl' '--with-libdir=/lib/x86_64-linux-gnu' '--enable-ftp' '--enable-calendar' '--with-gettext' '--with-xmlrpc' '--with-xsl' '--enable-fpm' '--with-fpm-user=daemon' '--with-fpm-group=daemon' '--enable-mbstring' '--enable-cgi' '--enable-ctype' '--enable-session' '--enable-mysqlnd' '--enable-intl' '--with-iconv' '--with-pdo_sqlite' '--with-sqlite3' '--with-readline' '--with-gmp' '--with-curl' '--with-pdo-pgsql=shared' '--with-pgsql=shared' '--with-config-file-scan-dir=/opt/bitnami/php/etc/conf.d' '--with-gd' '--with-freetype-dir=/usr' '--with-jpeg-dir=/usr' '--enable-zip' '--with-pdo-dblib=shared' '--with-tidy' '--with-password-argon2' '--with-ldap=/usr/' '--enable-apcu=shared'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /opt/bitnami/php/lib
Loaded Configuration File => /opt/bitnami/php/lib/php.ini
root@75f65cf46545:/#
```

**Comment by per-lind** [comment]
@miguelaeh unfortunately still not working but I can see the --with-password-argon2 option, could it be that the argon2 package was'nt detected when building PHP?
I did a new simple test like this
`echo '<?php ini_set('display_errors', 1); error_reporting(E_ALL); echo constant("PASSWORD_ARGON2ID") ?>' > /opt/bitnami/phpbb/test.php`

And the result is Warning: constant(): Couldn't find constant PASSWORD_ARGON2ID in /opt/bitnami/phpbb/test.php on line 1

**Comment by miguelaeh** [comment]
Hi @per-lind ,
I tested it using the following and it seems to be working:
```
root@6eeccc6e6d7f:/# echo "<?php print password_hash('somepassword', PASSWORD_ARGON2ID, ['memory_cost' => 2048, 'time_cost' => 4, 'threads' => 3]); ?>" > test.php
root@6eeccc6e6d7f:/# php test.php
$argon2id$v=19$m=2048,t=4,p=3$cS9VMm9JLlV6ZGl0UFVXNw$MLIk+uJGJ3FCAVjf7OjZQhdDUL5SlZMLXRA7F+EWYn8
```

Isn't' that the expected result?

**Comment by per-lind** [comment]
@miguelaeh We are getting closer :) From the command line/CLI it is working, the --with-password-argon2 option is there and your test works. But I took another look and it is missing when calling php using apache (no --with-password-argon2 in phpinfo(); and NULL output from the testfile.). I can see that the build dates differ in phpinfo and the /opt/bitnami/apache/modules/libphp7.so have a timestamp of Sep  3 18:25
Cloud it be that the apache module did not get rebuilt?

**Comment by miguelaeh** [comment]
Hi @per-lind ,
You are right. Let me rebuild libphp too.

**Comment by per-lind** [comment]
@miguelaeh just tried the latest 3.3.1-debian-10-r37 release image and it works all the way! Case closed :) Greate job

**Comment by miguelaeh** [comment]
Thanks @per-lind for the confirmation!!
